#Sponge launch configuration
#Mon Sep 01 00:55:50 CST 2025
additional-plugins-directory=${MODS_DIR}/plugins
args=--nogui
auto-download-libraries=true
check-library-hashes=true
libraries-directory=${BASE_DIR}/libraries
